# this is auto-generated by swagger-marshmallow-codegen
from marshmallow import (
    Schema,
    fields,
    INCLUDE,
)


class ServiceIssueQuery(Schema):
    label = fields.String()
    connection_id = fields.String()
    author = fields.String()
    service_id = fields.String()
    exchange_id = fields.String()
    state = fields.String()

    class Meta:
        unknown = INCLUDE


class ServiceIssue(Schema):
    service_id = fields.String()

    class Meta:
        unknown = INCLUDE


class ServiceIssueResponse(Schema):
    success = fields.Boolean()
    result = fields.List(fields.Nested(lambda: ServiceIssue()))

    class Meta:
        unknown = INCLUDE


class PDSSettingsExample(Schema):
    client_id = fields.String(missing=lambda: "1321wrf1g3f1412rsrfer")
    client_secret = fields.String(missing=lambda: "12341551513qw42as")
    optional_instance_name = fields.String(missing=lambda: "default")
    grant_type = fields.String(missing=lambda: "client_credentials")

    class Meta:
        unknown = INCLUDE


class PDSSetSettingsExampleResponse(Schema):
    success = fields.Boolean()
    result = fields.Nested(lambda: PDSSettingsExample())

    class Meta:
        unknown = INCLUDE


class PDSGetSettingsSchemaResponse(Schema):
    success = fields.Boolean()
    result = fields.Nested(lambda: PDSGetSettingsSchemaResponseResult())

    class Meta:
        unknown = INCLUDE


class PDSGetSettingsSchemaResponseResult(Schema):
    pds_name_1 = fields.Nested(lambda: PDSSettingsExample())
    pds_name_2 = fields.Field()

    class Meta:
        unknown = INCLUDE


class Payload(Schema):
    payload = fields.String()

    class Meta:
        unknown = INCLUDE


class DRIResponse(Schema):
    dri = fields.String()
    success = fields.Boolean(missing=lambda: True)

    class Meta:
        unknown = INCLUDE
